services:
  searxng:
    container_name: searxng
    image: searxng
    build:
      context: .
      dockerfile: searxng.dockerfile
    expose:
      - 4000
    ports:
      - 4000:8080
    networks:
      - AiSearch
  
  aisearch_backend:
    container_name: aisearch_backend
    image: backend
    build:
      context: .
      dockerfile: infrastructure/docker/backend.Dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=production
      - PORT=8000
      - SEARXNG_BASE_URL=http://searxng:8080
      - SEARXNG_API_URL=http://searxng:8080
      - BACKEND_PORT=8000
    depends_on:
        - searxng
    expose:
        - 8000
    ports:
        - 8000:8000
    networks:
        - AiSearch



networks:
  AiSearch:
    driver: bridge